# Generated by Django 3.1.3 on 2024-04-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201129_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Student', 'Student'), ('Professor', 'Professor')], default='employee', max_length=20, null=True),
        ),
    ]
