# Generated by Django 5.0.3 on 2024-03-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_student_user_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
