# Generated by Django 5.0.3 on 2024-03-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_student_college_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.AddField(
            model_name='admin',
            name='address',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='admin',
            name='college_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='admin',
            name='confirm_password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admin',
            name='dob',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='admin',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admin',
            name='personal_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='admin',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='admin',
            name='picture',
            field=models.ImageField(default='default_picture.jpg', upload_to='admin_pictures'),
        ),
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
