# Generated by Django 5.0.3 on 2024-03-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_admin_user_admin_address_admin_college_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
